apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-database-cm1
  labels:
    app: database
  {{- include "helm.labels" . | nindent 4 }}
  annotations:
    use-subpath: "true"
data:
  schema.sql: {{ .Values.databaseCm1.schemaSql | toYaml | indent 1 }}