apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-database
  labels:
  {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.type }}
  selector:
    app: database
    {{- include "helm.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.database.ports | toYaml | nindent 2 }}