apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm.fullname" . }}-database-data
  labels:
    app: database-data
  {{- include "helm.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.databaseData.storageRequest | quote }}