apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-get-item-info
  labels:
  {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.getItemInfo.type }}
  selector:
    app: get-item-info
    {{- include "helm.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.getItemInfo.ports | toYaml | nindent 2 }}