apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.fullname" . }}-default
  labels:
  {{- include "helm.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.default.serviceAccount.annotations | nindent 4 }}