quarkus.http.port=8086
quarkus.grpc.server.port=9094
quarkus.grpc.server.plain-text=true

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:SecReT-PasSwOrD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:database}

# ObjectManagement Service
objectmanagement.host=${GRPC_OBJECTS_HOST: localhost}
objectmanagement.port=${GRPC_OBJECTS_PORT: 9090}

# URLValidation Service
urlvalidation.host=${GRPC_URL_HOST: localhost}
urlvalidation.port=${GRPC_URL_PORT: 9092}