quarkus.http.port=8081
adapters.outbound.urlvalidation.UrlValidationClient/mp-rest/url=http://localhost:8080
#adapters.outbound.urlvalidation.UrlValidationClient/mp-rest/url
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=SecReT-PasSwOrD
quarkus.datasource.jdbc.url=jdbc:postgresql://host.docker.internal:5432/database

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# ObjectManagement Service
objectmanagement.host=localhost
objectmanagement.port=50051

# URLValidation Service
urlvalidation.host=localhost
urlvalidation.port=50052