quarkus.http.port=8082
quarkus.grpc.server.port=9093
quarkus.http.access-log.consolidate-rerouted-requests=true
quarkus.http.access-log.enabled=true
quarkus.config.log.values=false

# ObjectManagement Service
objectmanagement.host=${GRPC_OBJECTS_HOST: localhost}
objectmanagement.port=${GRPC_OBJECTS_PORT: 9090}

#PriceCheck Service
pricecheck.host=${GRPC_PRICECHECK_HOST: localhost}
pricecheck.port=${GRPC_PRICECHECK_PORT: 9094}

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:SecReT-PasSwOrD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:database}

mp.jwt.verify.publickey=${JWT_PUBLIC_KEY:-----BEGIN PUBLIC KEY-----\
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4JEqgNqMzO+9QnknqkEK\
27kaJ8iGvnGFyVFtzwUQuIdlZPjDr5U6SABgljdVGdZnpvKaK3ZWtzQjnXVLgpI8\
0l+2Lg+bVFX3mqQOlCwca3QLrfzmEUiK4tTrIGgtQnYBJVnXUWZKl2qYxDlMNwKG\
+d/FDZTnnierjiy3aZCLZtnVnQFH0SRolMJLECGeOufh8yep+8ClHHO57jvTLRk4\
T0EKakwqIRa5nQFO/WBczfZWsVNXUH7epxax6n1yklquchXtgT1JOjj/2w3IbmMz\
5KN0muPJfU9cfct18QUtvHzYor5CyOGeOxxzinhanlZAyfOOSU1bMXG7Uev7hENt\
QQIDAQAB\
-----END PUBLIC KEY-----}
mp.jwt.verify.issuer=AuthService
