services:
  database:
    image: postgres:17.2
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SecReT-PasSwOrD
      POSTGRES_DB: database
    volumes:
      - db_data:/var/lib/postgresql/data
      # Mount schema.sql so it's run automatically on container creation
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5

  userservice:
    build:
      context: ./UserService/
      dockerfile: Dockerfile
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: database
      DB_USERNAME: postgres
      DB_PASSWORD: SecReT-PasSwOrD
    ports:
      - "8080:8080"
    expose:
      - 9091
    depends_on:
      database:
        condition: service_healthy

  authservice:
    build:
      context: ./AuthService/
      dockerfile: Dockerfile
    environment:
      JWT_PRIVATE_KEY: -----BEGIN PRIVATE KEY-----MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDgkSqA2ozM771CeSeqQQrbuRonyIa+cYXJUW3PBRC4h2Vk+MOvlTpIAGCWN1UZ1mem8pordla3NCOddUuCkjzSX7YuD5tUVfeapA6ULBxrdAut/OYRSIri1OsgaC1CdgElWddRZkqXapjEOUw3Aob538UNlOeeJ6uOLLdpkItm2dWdAUfRJGiUwksQIZ465+HzJ6n7wKUcc7nuO9MtGThPQQpqTCohFrmdAU79YFzN9laxU1dQft6nFrHqfXKSWq5yFe2BPUk6OP/bDchuYzPko3Sa48l9T1x9y3XxBS28fNiivkLI4Z47HHOKeFqeVkDJ845JTVsxcbtR6/uEQ21BAgMBAAECggEAAL73gHpGLNyANfGeFdAyf4laLDCoornqaY4WMP5bNsNOxtEwVGuvLmCl8Xz/xBHn9T0c3jEXitmm/QjQAxm5dWXXZPuTSgPt4+5QlOIF1CUmCfvRlDqEwsnvRmou+eekPrueKslas3pDEj/LrR3nVRQog1BWNqD66AJMN6ynWErP9Ycr5UnX8oNU3mRZ4EekNSbPkjH+tSe7wbXnp1wER8cPeRN6R6GW6mcm/eTlJ2ovqCQ/Xg/ExbpKrh5p8IoqCMuTW8z5MDcrt0x7F4E8bbDIymrOaw7Z4Xq/ZEVyefNQo7y22Sp9G5ri4U2kKYCTAOHuakbJNb18nxKKnNv7gQKBgQDyJLs7kydBAauR7tHFCN6w/iocC0i3oZ72AiMbS1/Z02uzUQZKnfhdByJ9hyZLnSj9U/+TgGG0KvptAulCn01FTEHqs6vvvlrqhq3tf6sG+bfhlgOiUZ39czRK0C1iKmI9Yek5EK9GB/Crsqm0NTq1mjwBVlxw2aKPSlA+X+TfkQKBgQDtavMd7aBzALXZFnhWg2PAqfHEuwDrihHmU0VT+DgWZ+mBvfYUTQ/XttWI2jI/3QdbGIe6+5S31f5kLAZrRVzvIknkuiCXO7W2O5DnD7r1YejGK5E02njhiJ3nuasNx0Qg5Sn1C+EeWfvR9+KQXplcjYPuElZL6hlNAPMCo346sQKBgQDTTpiRoZXE1ddKT3WBk376R6KpvHMlxIW6uxy1ye4IYcZ/wjpSTU6aqApCLvmNTMWjZHUI3CTnHAZTsRGr0OaWjbiMP2TQn3YpaYRIWHwAZ1U/KDFdqgnMToeYrdic7M20MUhcQyIhY/Zzb0NG/piQN9sbc6jR1ipVDw29kONi8QKBgGAXQlDhpWgGaJN1mb0CLrSC0/yY53Vti3MaTtv+gcznv8WoOdnbmsbnFCPwlBfvAJQpKH5QZs/FB9JJU0vFZijPSvMNNjWfkBsynqI2Zqf8ObdDWOD4b6ZwoeBw8D+CYBukRMgOR83+A4Lm/kcKUq34BOate0n8dMMK2FBAFc3xAoGAFnI8QxlXWPpAvaN+jTNPYHDBGSb2xf2jpPUhX8EB1ETfredJlcafVKdgCu1OQnZUqnOGHh6qsGBuondcepuw3d8NegrRjKf9AgKnqqUXHZLKEpiuAnUJDDUope8xAtKHbBTu+jV8XDQyhDbfmmMC+vrYnO3FlPBnB/sXgtrP9m8=-----END PRIVATE KEY-----
      USERSERVICE_URL: http://userservice:8080/user
    ports:
      - "8081:8081"
    depends_on:
      - userservice

  object-management:
    build:
      context: ./object-management
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: SecReT-PasSwOrD
      DB_PORT: 5432
      DB_HOST: database
      DB_NAME: database
      JWT_PUBLIC_KEY: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4JEqgNqMzO+9QnknqkEK27kaJ8iGvnGFyVFtzwUQuIdlZPjDr5U6SABgljdVGdZnpvKaK3ZWtzQjnXVLgpI80l+2Lg+bVFX3mqQOlCwca3QLrfzmEUiK4tTrIGgtQnYBJVnXUWZKl2qYxDlMNwKG+d/FDZTnnierjiy3aZCLZtnVnQFH0SRolMJLECGeOufh8yep+8ClHHO57jvTLRk4T0EKakwqIRa5nQFO/WBczfZWsVNXUH7epxax6n1yklquchXtgT1JOjj/2w3IbmMz5KN0muPJfU9cfct18QUtvHzYor5CyOGeOxxzinhanlZAyfOOSU1bMXG7Uev7hENtQQIDAQAB-----END PUBLIC KEY-----
    ports:
      - "8082:8080"
      - "9090:9090" # TODO: Remove this port when the gRPC is secured
    depends_on:
      database:
        condition: service_healthy

  interval-monitor:
    build:
      context: ./interval-monitor
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: SecReT-PasSwOrD
      DB_PORT: 5432
      DB_HOST: database
      DB_NAME: database
      JWT_PUBLIC_KEY: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4JEqgNqMzO+9QnknqkEK27kaJ8iGvnGFyVFtzwUQuIdlZPjDr5U6SABgljdVGdZnpvKaK3ZWtzQjnXVLgpI80l+2Lg+bVFX3mqQOlCwca3QLrfzmEUiK4tTrIGgtQnYBJVnXUWZKl2qYxDlMNwKG+d/FDZTnnierjiy3aZCLZtnVnQFH0SRolMJLECGeOufh8yep+8ClHHO57jvTLRk4T0EKakwqIRa5nQFO/WBczfZWsVNXUH7epxax6n1yklquchXtgT1JOjj/2w3IbmMz5KN0muPJfU9cfct18QUtvHzYor5CyOGeOxxzinhanlZAyfOOSU1bMXG7Uev7hENtQQIDAQAB-----END PUBLIC KEY-----
    ports:
      - "8083:8080"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    environment:
      JWT_PUBLIC_KEY: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4JEqgNqMzO+9QnknqkEK27kaJ8iGvnGFyVFtzwUQuIdlZPjDr5U6SABgljdVGdZnpvKaK3ZWtzQjnXVLgpI80l+2Lg+bVFX3mqQOlCwca3QLrfzmEUiK4tTrIGgtQnYBJVnXUWZKl2qYxDlMNwKG+d/FDZTnnierjiy3aZCLZtnVnQFH0SRolMJLECGeOufh8yep+8ClHHO57jvTLRk4T0EKakwqIRa5nQFO/WBczfZWsVNXUH7epxax6n1yklquchXtgT1JOjj/2w3IbmMz5KN0muPJfU9cfct18QUtvHzYor5CyOGeOxxzinhanlZAyfOOSU1bMXG7Uev7hENtQQIDAQAB-----END PUBLIC KEY-----
      NEXTAUTH_SECRET: 9n0Gnw+JJ64DsMSXdejaLVNNlLtVzNmhijQlYorTa3Q=
      NEXTAUTH_URL: http://localhost:8081
    ports:
      - "3000:3000"
    depends_on:
      - authservice

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4000:4000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - userservice
      - authservice
      - object-management
      - interval-monitor
      # - frontend

  order-list:
    build:
      context: ./order-list
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: SecReT-PasSwOrD
      DB_PORT: 5432
      DB_HOST: database
      DB_NAME: database
      JWT_PUBLIC_KEY: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4JEqgNqMzO+9QnknqkEK27kaJ8iGvnGFyVFtzwUQuIdlZPjDr5U6SABgljdVGdZnpvKaK3ZWtzQjnXVLgpI80l+2Lg+bVFX3mqQOlCwca3QLrfzmEUiK4tTrIGgtQnYBJVnXUWZKl2qYxDlMNwKG+d/FDZTnnierjiy3aZCLZtnVnQFH0SRolMJLECGeOufh8yep+8ClHHO57jvTLRk4T0EKakwqIRa5nQFO/WBczfZWsVNXUH7epxax6n1yklquchXtgT1JOjj/2w3IbmMz5KN0muPJfU9cfct18QUtvHzYor5CyOGeOxxzinhanlZAyfOOSU1bMXG7Uev7hENtQQIDAQAB-----END PUBLIC KEY-----
    ports:
      - "8084:8080"
      - "9093:9093"
    depends_on:
      - database

  url-validator:
    build:
      context: ./url-validator
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8085:8080"
      - "9092:9092"

  get-item-info:
    build:
      context: ./get-item-info
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: SecReT-PasSwOrD
      DB_PORT: 5432
      DB_HOST: database
      DB_NAME: database
    ports:
      - "8086:8080"
    depends_on:
      - database

volumes:
  db_data:
