version: '3.8'

services:
  database:
    image: postgres:17.2
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SecReT-PasSwOrD
      POSTGRES_DB: database
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5

  object-management:
    build:
      context: ./object-management
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: SecReT-PasSwOrD
      DB_PORT: 5432
      DB_HOST: database
      DB_NAME: database
    depends_on:
      database:
        condition: service_healthy

volumes:
  db_data: