events {}

http {
    upstream user {
        server userservice:8080;
    }

    upstream auth {
        server authservice:8081;
    }

    upstream object {
        server object-management:8085;
    }

    upstream interval {
        server interval-monitor:8081;
    }

    upstream frontend {
        server frontend:3000;
    }

server {
    listen 4000;

    location /user/ {
        rewrite ^/user/(.*) /$1 break;
        proxy_pass http://user/;
    }

    location /auth/ {
        rewrite ^/auth/(.*) /$1 break;
        proxy_pass http://auth/;
    }

    location /object/ {
        rewrite ^/object/(.*) /$1 break;
        proxy_pass http://object/;
    }

    location /interval/ {
        rewrite ^/interval/(.*) /$1 break;
        proxy_pass http://interval/;
    }

    location /frontend/ {
        rewrite ^/frontend/(.*) /$1 break;
        proxy_pass http://frontend/;
    }
}

}