events {}

http {
    upstream userservice {
        server userservice:8080;
    }

    upstream authservice {
        server authservice:8081;
    }

    upstream objectmanagement {
        server object-management:8082;
    }

    upstream intervalmonitor {
        server interval-monitor:8083;
    }


    server {
        listen 4000;

        location /user/ {
            proxy_pass http://userservice/;
            rewrite ^/userservice/(.*) /$1 break;
        }

        location /auth/ {
            proxy_pass http://authservice/;
            rewrite ^/authservice/(.*) /$1 break;
        }

        location /object/ {
            proxy_pass http://objectmanagement/;
            rewrite ^/object-management/(.*) /$1 break;
        }

        location /interval/ {
            proxy_pass http://intervalmonitor/;
            rewrite ^/interval-monitor/(.*) /$1 break;
        }
    }
}