apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-authservice
  labels:
  {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.authservice.replicas }}
  selector:
    matchLabels:
      app: authservice
    {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: authservice
      {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: JWT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-keys
              key: private.key
        - name: USERSERVICE_URL
          value: http://{{ include "helm.fullname" . }}-userservice:8080/user
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.authservice.authservice.image }}
        name: authservice
        resources:
          {{ include "helm.resources" (list "authservice" .) | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.authservice.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.authservice.readinessProbe | nindent 10 }}
