apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-docs
  labels:
  {{- include "helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: docs
    {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: docs
      {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ quote .Values.docs.docs.image }}
        name: docs
        resources: {}