apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "helm.fullname" . }}-routes
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/rest/user/`)
      kind: Rule
      priority: 10
      services:
        - name: {{ include "helm.fullname" . }}-userservice
          port: 8080
          weight: 1
      middlewares:
        - name: strip-prefix-user

    - match: PathPrefix(`/rest/auth/`)
      kind: Rule
      priority: 10
      services:
        - name: {{ include "helm.fullname" . }}-authservice
          port: 8080
          weight: 1
      middlewares:
        - name: strip-prefix-auth

    - match: PathPrefix(`/rest/object/`)
      kind: Rule
      priority: 10
      services:
        - name: {{ include "helm.fullname" . }}-object-management
          port: 8080
          weight: 1
      middlewares:
        - name: strip-prefix-object

    - match: PathPrefix(`/rest/order/`)
      kind: Rule
      priority: 10
      services:
        - name: {{ include "helm.fullname" . }}-order-list
          port: 8080
          weight: 1
      middlewares:
        - name: strip-prefix-order

    - match: PathPrefix(`/rest/interval/`)
      kind: Rule
      priority: 5
      services:
        - name: {{ include "helm.fullname" . }}-interval-monitor
          port: 8080
          weight: 1
      middlewares:
        - name: strip-prefix-interval

    - match: PathPrefix(`/docs`)
      kind: Rule
      priority: 5
      services:
        - name: {{ include "helm.fullname" . }}-docs
          port: 80
          weight: 1

    - match: PathPrefix(`/`)
      kind: Rule
      priority: 1
      services:
        - name: {{ include "helm.fullname" . }}-frontend
          port: 3000
          weight: 1
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-user
spec:
  stripPrefix:
    prefixes:
      - /rest/user
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-auth
spec:
  stripPrefix:
    prefixes:
      - /rest/auth
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-object
spec:
  stripPrefix:
    prefixes:
      - /rest/object
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-order
spec:
  stripPrefix:
    prefixes:
      - /rest/order
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-interval
spec:
  stripPrefix:
    prefixes:
      - /rest/interval
