apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-interval-monitor
  labels:
  {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.intervalMonitor.replicas }}
  selector:
    matchLabels:
      app: interval-monitor
    {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: interval-monitor
      {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: "{{ include "helm.fullname" . }}-{{ .Values.global.database.name }}"
        - name: DB_NAME
          value: {{ quote .Values.global.database.name }}
        - name: DB_PASSWORD
          value: {{ quote .Values.global.database.password }}
        - name: DB_PORT
          value: {{ quote .Values.global.database.port }}
        - name: DB_USERNAME
          value: {{ quote .Values.global.database.username }}
        - name: GRPC_OBJECTS_HOST
          value: "{{ include "helm.fullname" . }}-{{ .Values.intervalMonitor.intervalMonitor.env.grpcObjectsHost }}"
        - name: GRPC_OBJECTS_PORT
          value: {{ quote .Values.intervalMonitor.intervalMonitor.env.grpcObjectsPort }}
        - name: GRPC_ORDERLIST_HOST
          value: "{{ include "helm.fullname" . }}-{{ .Values.intervalMonitor.intervalMonitor.env.grpcOrderlistHost }}"
        - name: GRPC_ORDERLIST_PORT
          value: {{ quote .Values.intervalMonitor.intervalMonitor.env.grpcOrderlistPort}}
        - name: GRPC_USERS_HOST
          value: "{{ include "helm.fullname" . }}-{{ .Values.intervalMonitor.intervalMonitor.env.grpcUsersHost }}"
        - name: GRPC_USERS_PORT
          value: {{ quote .Values.intervalMonitor.intervalMonitor.env.grpcUsersPort }}
        - name: JWT_PUBLIC_KEY
          value: {{ quote .Values.global.jwt.publicKey }}
        - name: MOCK_ENABLED
          value: {{ quote .Values.intervalMonitor.intervalMonitor.env.mockEnabled }}
        image: {{ .Values.intervalMonitor.intervalMonitor.image }}
        name: interval-monitor
        resources: {}
        livenessProbe:
          {{- toYaml .Values.intervalMonitor.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.intervalMonitor.readinessProbe | nindent 10 }}