apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-order-list
  labels:
  {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.orderList.replicas }}
  selector:
    matchLabels:
      app: order-list
    {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: order-list
      {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: "{{ include "helm.fullname" . }}-{{ .Values.global.database.name }}"
        - name: DB_NAME
          value: {{ quote .Values.global.database.name }}
        - name: DB_PASSWORD
          value: {{ quote .Values.global.database.password }}
        - name: DB_PORT
          value: {{ quote .Values.global.database.port }}
        - name: DB_USERNAME
          value: {{ quote .Values.global.database.username }}
        - name: GRPC_OBJECTS_HOST
          value: "{{ include "helm.fullname" . }}-{{ .Values.orderList.orderList.env.grpcObjectsHost }}"
        - name: GRPC_OBJECTS_PORT
          value: {{ quote .Values.orderList.orderList.env.grpcObjectsPort }}
        - name: GRPC_PRICECHECK_HOST
          value: "{{ include "helm.fullname" . }}-{{ .Values.orderList.orderList.env.grpcPricecheckHost }}"
        - name: GRPC_PRICECHECK_PORT
          value: {{ quote .Values.orderList.orderList.env.grpcPricecheckPort }}
        - name: JWT_PUBLIC_KEY
          value: {{ quote .Values.global.jwt.publicKey }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.orderList.orderList.image }}
        name: order-list
        resources: {}
      restartPolicy: Always