apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-userservice
  labels:
  {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.userservice.replicas }}
  selector:
    matchLabels:
      app: userservice
    {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: userservice
      {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: "{{ include "helm.fullname" . }}-{{ .Values.global.database.name }}"
        - name: DB_NAME
          value: {{ quote .Values.global.database.name }}
        - name: DB_PASSWORD
          value: {{ quote .Values.global.database.password }}
        - name: DB_PORT
          value: {{ quote .Values.global.database.port }}
        - name: DB_USERNAME
          value: {{ quote .Values.global.database.username }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.userservice.image }}
        livenessProbe:
            exec:
              command:
                - curl localhost:8080/actuator/health | grep UP || exit 1
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 17
        name: userservice
        resources: {}
      restartPolicy: Always