# This Dockerfile is used to build the image for the GitHub Actions workflow.
# The maven install and package commands are run in the actions workflow, so the image only needs to copy the built application files.
# This speeds up the image build process because the dependencies are already installed and cached.
# For a normal multi-stage build, please visit the Dockerfile file.
FROM eclipse-temurin:23-jre-alpine
WORKDIR /app
COPY build/libs/*.jar /app/app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]