events {}

http {
    upstream user {
        server userservice:8080;
    }

    upstream auth {
        server authservice:8081;
    }

    upstream object {
        server object-management:8080;
    }

    upstream interval {
        server interval-monitor:8081;
    }

    upstream docs {
        server docs:80;
    }

    # upstream frontend {
    #     server frontend:3000;
    # }

    upstream order {
        server order-list:8082;
    }

    server {
        listen 4000;

        location /rest/user/ {
            rewrite ^/rest/user/(.*) /$1 break;
            proxy_pass http://user/;
        }

        location /rest/auth/ {
            rewrite ^/rest/auth/(.*) /$1 break;
            proxy_pass http://auth/;
        }

        location /rest/object/ {
            rewrite ^/rest/object/(.*) /$1 break;
            proxy_pass http://object/;
        }

        location /rest/interval/ {
            rewrite ^/rest/interval/(.*) /$1 break;
            proxy_pass http://interval/;
        }

        location /rest/order/ {
            rewrite ^/rest/order/(.*) /$1 break;
            proxy_pass http://order/;
        }

        location /docs/ {
            rewrite ^/docs/(.*) /$1 break;
            proxy_pass http://docs/;
        }

        # location / {
        #     proxy_pass http://frontend/;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #     proxy_set_header X-Forwarded-Proto $scheme;
        # }
    }
}