apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-cloud.yml --out kubernetes
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: authservice
  name: authservice
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: authservice
