apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: docs
  name: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: docs
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: docs
    spec:
      containers:
        - image: ghcr.io/robert27/thi-case-cnd-project/docs:latest
          name: docs
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
