apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-item-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-item-info
  template:
    metadata:
      labels:
        app: get-item-info
    spec:
      containers:
        - name: get-item-info
          image: ghcr.io/robert27/thi-case-cnd-project/get-item-info:latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: database
            - name: DB_NAME
              value: database
            - name: DB_PASSWORD
              value: SecReT-PasSwOrD
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: postgres
            - name: GRPC_OBJECTS_HOST
              value: object-management
            - name: GRPC_OBJECTS_PORT
              value: "9090"
            - name: GRPC_URL_HOST
              value: url-validator
            - name: GRPC_URL_PORT
              value: "9092"
