apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: get-item-info
  name: get-item-info
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "9094"
      port: 9094
      targetPort: 9094
  selector:
    io.kompose.service: get-item-info
