apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: get-item-info
  name: get-item-info
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "9094"
      port: 9094
      targetPort: 9094
  selector:
    io.kompose.service: get-item-info
