apiVersion: v1
kind: Service
metadata:
  name: object-management
spec:
  ports:
    - port: 8080
      name: object-http
    - port: 9090
      name: object-grpc
  selector:
    app: object-management
