apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-validator
  template:
    metadata:
      labels:
        app: url-validator
    spec:
      containers:
        - name: url-validator
          image: ghcr.io/robert27/thi-case-cnd-project/url-validator:latest
          imagePullPolicy: Always
