apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-cloud.yml --out kubernetes
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: userservice
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: userservice
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-cloud.yml --out kubernetes
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: userservice
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: database
            - name: DB_NAME
              value: database
            - name: DB_PASSWORD
              value: SecReT-PasSwOrD
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: postgres
          image: ghcr.io/robert27/thi-case-cnd-project/user-service:main
          name: userservice
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9019
              protocol: TCP
      restartPolicy: Always
