quarkus.grpc.clients.objects.port=${GRPC_OBJECTS_PORT:9090}
quarkus.grpc.clients.objects.host=${GRPC_OBJECTS_HOST:localhost}
quarkus.grpc.clients.users.port=${GRPC_USERS_PORT:9091}
quarkus.grpc.clients.users.host=${GRPC_USERS_HOST:localhost}
quarkus.grpc.clients.order.port=${GRPC_ORDERLIST_PORT:9093}
quarkus.grpc.clients.order.host=${GRPC_ORDERLIST_HOST:localhost}
quarkus.http.port=8081
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:SecReT-PasSwOrD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:database}
quarkus.datasource.jdbc.max-size=16
