quarkus.grpc.clients.objects.host=localhost
quarkus.grpc.clients.objects.port=9090
quarkus.grpc.clients.users.host=localhost
quarkus.grpc.clients.users.port=9091
quarkus.http.port=8081
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:SecReT-PasSwOrD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:database}
quarkus.datasource.jdbc.max-size=16
