quarkus.http.port=8082
quarkus.http.access-log.consolidate-rerouted-requests=true
quarkus.http.access-log.enabled=true
quarkus.config.log.values=false
objectmanagement.host=localhost
objectmanagement.port=50051
pricecheck.host=localhost
pricecheck.port=50052
quarkus.grpc.server.port=9093
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=SecReT-PasSwOrD
quarkus.datasource.jdbc.url=jdbc:postgresql://host.docker.internal:5432/database
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
# Konfiguration f�r den Price Monitoring REST-Client
quarkus.rest-client."price-monitoring".url=http://localhost:8081
# Object Management Service
mp.rest.client."orderlistservice.adapters.outbound.client.ObjectManagementClient".url=http://localhost:8083
# Cycle Service
mp.rest.client."orderlistservice.adapters.outbound.client.CycleServiceClient".url=http://localhost:8080
# Optional: Logging Configuration
quarkus.log.level=INFO
quarkus.log.console.enable=true
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
