create table if not exists users
(
    user_id       integer generated by default as identity
        primary key,
    password_hash varchar(255),
    username      varchar(255)
);

create table categories
(
    id          serial
        primary key,
    name        varchar(100) not null
        unique,
    description text
);

create table objects
(
    id               serial
        primary key,
    name             varchar(255) not null,
    description      text,
    category_id      integer
                                  references categories
                                      on delete set null,
    reorder_url      text,
    created_at       timestamp             default CURRENT_TIMESTAMP,
    user_id          bigint       not null,
    reorder_interval interval,
    quantity         integer      not null default 1,
    weekday          integer,
    constraint unique_reorder_url
        unique (user_id, reorder_url),
    constraint unique_category_name
        unique (user_id, category_id, name),
    constraint fk_user
        foreign key (user_id)
            references users (user_id) on delete cascade
);

CREATE TABLE item_price_log
(
    id         SERIAL PRIMARY KEY,
    item_id    INTEGER        NOT NULL,
    price      NUMERIC(10, 2) NOT NULL,
    available  INTEGER        NOT NULL,
    checked_at TIMESTAMP      NOT NULL,
    CONSTRAINT fk_item
        FOREIGN KEY (item_id)
            REFERENCES objects (id)
            ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS order_object
(
    id           SERIAL PRIMARY KEY,
    item_id      INTEGER   NOT NULL,
    log_id       INTEGER,
    cycle_time   TIMESTAMP NOT NULL,
    order_status VARCHAR(20) CHECK (order_status IN ('OPEN', 'DONE', 'FAILED', 'ABORTED')),
    item_status  BOOLEAN   NOT NULL,
    CONSTRAINT fk_log
        FOREIGN KEY (log_id)
            REFERENCES item_price_log (id),
    CONSTRAINT fk_item
        FOREIGN KEY (item_id)
            REFERENCES objects (id)
);

CREATE TABLE IF NOT EXISTS interval_status
(
    id         SERIAL PRIMARY KEY,
    user_id    BIGINT    NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user
        FOREIGN KEY (user_id)
            REFERENCES users (user_id) ON DELETE CASCADE
);


INSERT INTO categories (name, description)
VALUES ('Cleaning Supplies', 'Products for cleaning and maintaining household hygiene'),
       ('Groceries', 'Everyday food and beverage items for your kitchen and pantry'),
       ('Personal Care', 'Hygiene and grooming products for personal use'),
       ('Pet Supplies', 'Food, toys, and accessories for your pets'),
       ('Office Supplies', 'Stationery, paper, and office essentials'),
       ('Laundry Supplies', 'Detergents, fabric softeners, and stain removers for laundry'),
       ('Kitchen Essentials', 'Utensils, cookware, and tools for cooking and dining'),
       ('Toiletries', 'Soap, shampoo, toothpaste, and other bathroom essentials'),
       ('Baby Care', 'Diapers, wipes, and baby food for infant care'),
       ('Health & Wellness', 'Vitamins, supplements, and first-aid supplies'),
       ('Storage & Organization', 'Bins, boxes, and shelves to organize your home'),
       ('Home Maintenance', 'Tools, hardware, and repair kits for home upkeep'),
       ('Garden Supplies', 'Seeds, fertilizers, and tools for gardening'),
       ('Beverages', 'Bottled drinks, tea, coffee, and juices'),
       ('Snacks & Treats', 'Chips, candies, and other snackable items')
ON CONFLICT (name)
    DO NOTHING;

