quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:SecReT-PasSwOrD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:database}:${DB_PORT:5432}/${DB_NAME:database}
quarkus.datasource.jdbc.max-size=16
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4000, http://localhost:3000
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS, HEAD