syntax = "proto3";

option java_multiple_files = false;
option java_package = "dev.eggl.objects";
option java_outer_classname = "StorageObjectsProto";

package objects;

// The storage service definition.
service ObjectService {
  rpc FindAllDayUsers (DayUsersRequest) returns (DayUsersReply) {}
}

// The request message for finding all day users.
message DayUsersRequest {
  int32 weekDay = 1;         // Integer for the weekday
  repeated int32 userIds = 2; // List of user IDs
}

// The response message containing storage object IDs grouped by user ID.
message DayUsersReply {
  repeated UserObjectIds userObjectIds = 1;
}

// The message for grouping storage object IDs by user ID.
message UserObjectIds {
  int32 userId = 1;           // User ID
  repeated int32 objectIds = 2; // List of object IDs for the user
}

