# Use Node.js as the base image for building the app
# Final stage: Use Nginx to serve the built application
FROM nginx:alpine AS release
# Copy your custom nginx configuration, if applicable
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy built files from the build stage
COPY .vitepress/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
