spring.application.name=AuthService
server.port=8081
userservice.url=${USERSERVICE_URL:localhost}

#health
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always